### ISSUE TITLE
卡死问题什么时候能解决呢？

### ISSUE THREAD

**Issue by huzhangjunn** [Airsaid/AndroidLocalizePlugin#10]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by lgengsy** [comment]
同样遇到这个问题啊。每次都会卡死 。

**Comment by Airsaid** [comment]
目前全力开发公司项目中，暂时抽不出时间更新。

欢迎大家 PR 啊~

**Comment by andyliuzs** [comment]
文字量大了，卡死，也生成不了国际化文件。。。可以说不能用

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本，该版本修复了卡死问题。
