### ISSUE TITLE
Translation failure HttpRetryException

### ISSUE THREAD

**Issue by jstokke** [Airsaid/AndroidLocalizePlugin#105]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [X] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [X ] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version: 2.9.0
- IDE Version: 2022.1.1

#### Issue details

I'm getting this error:

Translation failure: Failed to translate "Disabled" text from Auto language to Arabic language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

I tried multiple languages, all gave the same error.

**Comment by Airsaid** [comment]
Duplicate issue: https://github.com/Airsaid/AndroidLocalizePlugin/issues/83
