### ISSUE TITLE
What is "translation interval time"?

### ISSUE THREAD

**Issue by DankalApps** [Airsaid/AndroidLocalizePlugin#109]
I noticed setting "Translation interval(second)" anddidn't know what it means. Searched whole internet and found no single clue.

**Comment by Airsaid** [comment]
As the translation service limits frequent API calls, this option is to control the time between each translation so as to avoid triggering the limit.

**Comment by DankalApps** [comment]
Thank you for information!

FYI: Google (default, not API) still blocked me after setting longest possible translation interval (10 seconds).

**Comment by Airsaid** [comment]
Google (default, not API) is not very stable, you can switch to another translator, e.g. Google (API), if you don't have the API KEY, you can apply for it first. Using your own API KEY will be more stable.

**Comment by DankalApps** [comment]
Thanks, I have a hell trying to make google cloud account (will have to acquire new credit card just for that..). So API is not an option for me now. 

I will just do like 2 languages every hour or so and maybe that will stop the blocking. And I have an improvement idea for you (but will make another issue to not make it offtopic)
