### ISSUE TITLE
Tags with empty bodies 

### ISSUE THREAD

**Issue by psydj1** [Airsaid/AndroidLocalizePlugin#11]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ X ] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version: 1.3
- IDE Version: 3.2.1

#### Issue details
After translation I get tags with empty bodies for any language:

< string name="app_name"></ string >
< string name="tour_text_a"></ string >
< string name="tour_text_b"></ string >
< string name="tour_text_c"></ string >
< string name="tour_text_d"></ string >
< string name="tour_text_e"></ string >

I tried removing the plugin and installing again

Thank you

**Comment by Airsaid** [comment]
Thanks for the feedback. I will fix it soon.

**Comment by LinhNH17** [comment]
Faulty in the German language, Russian, Spanish

**Comment by zhangjizxc** [comment]
> Thanks for the feedback. I will fix it soon.

token的原因 吧

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本，该版本新增了代理功能，如果翻译字符为空，可以尝试添加代理解决。
