### ISSUE TITLE
Add support for OpenAI GPT-3

### ISSUE THREAD

**Issue by rbenza** [Airsaid/AndroidLocalizePlugin#112]
The OpenAI GPT-3 API has even better translation quality compared to DeepL. Would be great if this service could also be included.

**Comment by Airsaid** [comment]
This is a good idea and I will support it in the next release.

**Comment by rbenza** [comment]
Nice, I've just donated 10 dollars for your great work with this plugin. It's really useful. Keep up the good work!

**Comment by Airsaid** [comment]
Thank you so much for your donation! It has been very helpful to me in the ongoing development of the project.

**Comment by rbenza** [comment]
Hi, any timeline on the new version? I could maybe create some time for a PR to support OpenAI. But only if you're not already started the work otherwise would be waste of time :)

**Comment by Airsaid** [comment]
Sorry, I've been busy with other things lately. So, welcome PRs!

**Comment by Airsaid** [comment]
https://github.com/Airsaid/AndroidLocalizePlugin/pull/118
