### ISSUE TITLE
java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

### ISSUE THREAD

**Issue by mariodantas** [Airsaid/AndroidLocalizePlugin#113]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [X ] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [X] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version: 2.9.0
- IDE Version: 2022.1.1 Patch 2

#### Issue details
ERROR:

Translation failure: Failed to translate "Creating user" text from Auto language to Spanish language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Airsaid** [comment]
Duplicate issue: https://github.com/Airsaid/AndroidLocalizePlugin/issues/83
