### ISSUE TITLE
在string.xml右键选择翻译时报错，如图

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#13]
![image](https://user-images.githubusercontent.com/4145405/56497873-ec134700-6531-11e9-812e-c2fd4e8a5588.png)

**Comment by Airsaid** [comment]
谢谢反馈，可以附带上你的 AndroidStudio 版本信息吗？我排查下问题。

**Comment by qyzhaojinxi** [comment]
AndroidStudio 3.2版本，Mac OS 10.14.4

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本，该版本修复了该问题。
