### ISSUE TITLE
翻译得到的全是空文本

### ISSUE THREAD

**Issue by iamjiangyong** [Airsaid/AndroidLocalizePlugin#14]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ ] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by iamjiangyong** [comment]
经常性卡死

**Comment by izengzehong** [comment]
我的是插件1.3，as是3.4.1，翻译的全是空字符串

**Comment by zhangjizxc** [comment]
这个还不如可以配置key...no need key的意思是大家共用Key.. 大家共用额度，额度用完了，当然就空了。

**Comment by KnIfER** [comment]
IP被谷歌封禁或者无法连接谷歌翻译

**Comment by KnIfER** [comment]
可以开一个谷歌翻译的网页测试连接。会出现“translation error”

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本，该版本新增了代理功能，如果翻译字符为空，可以尝试添加代理解决。
