### ISSUE TITLE
卡死人不偿命

### ISSUE THREAD

**Issue by mosnster** [Airsaid/AndroidLocalizePlugin#15]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [1 ] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_
啥时候能解决一下啊，哥

**Comment by FZUczh** [comment]
一样卡死

**Comment by KnIfER** [comment]
卡的问题已经被我解决
https://github.com/Airsaid/AndroidLocalizePlugin/issues/21

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本，该版本新增了代理功能，如果翻译字符为空，可以尝试添加代理解决。
