### ISSUE TITLE
期望有全选按钮

### ISSUE THREAD

**Issue by renyuzhuo** [Airsaid/AndroidLocalizePlugin#16]
期望选择语言时有全选按钮，每一个分别勾选比较麻烦，谢谢！

Android Studio 3.6 Canary 4
Build #AI-191.7479.19.36.5679705, built on June 22, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by Airsaid** [comment]
原本是有全选按钮，但是会导致翻译量过大导致 IP 被暂时封禁，所以后来又去掉了... 所以全选按钮会在增加代理 IP 功能后再增加上~

**Comment by KnIfER** [comment]
IP封禁好麻烦，每次都要等待全部结束，然后换个vpn节点重新开始……
所以特别希望能够 保存/加载 要翻译的语言，一次翻译一部分。

我现在都是开一个空项目，在空项目里面用这个插件机翻，完了再用脚本搬回来，不敢在原项目使用……

**Comment by KnIfER** [comment]
有了， 我直接加一个序列化和重新初始化的输入框：  
![Screenshot (7)](https://user-images.githubusercontent.com/11593903/66255990-33c61c00-e7bc-11e9-8de4-44bc124ca270.png)

**Comment by renyuzhuo** [comment]
> 有了， 我直接加一个序列化和重新初始化的输入框：
> ![Screenshot (7)](https://user-images.githubusercontent.com/11593903/66255990-33c61c00-e7bc-11e9-8de4-44bc124ca270.png)

cool

**Comment by Airsaid** [comment]
V1.5 版本加上了全选按钮，更新到 1.5 版本即可。
