### ISSUE TITLE
String Escapes

### ISSUE THREAD

**Issue by MitjaHenner** [Airsaid/AndroidLocalizePlugin#17]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [X] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version: latest
- IDE Version: 3.4.2

#### Issue details
Escapes in string resources break the translation.

When translating remove every "\" from the source string and it would be great if you could escape the translated strings after.

**Comment by Airsaid** [comment]
Hi, you can update to V1.4 and set the xliff: g tag to ignore characters or text you don't want to translate.
