### ISSUE TITLE
Not ignoring parts of strings marked to ignore

### ISSUE THREAD

**Issue by scudderfish** [Airsaid/AndroidLocalizePlugin#18]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ X] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:1.3
- IDE Version:Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic

#### Issue details
According to https://developer.android.com/guide/topics/resources/localization, it should be possible to mark sections to be not translated with <xliff:g></xliff:g>, such as number placeholders and embedded format strings.  However the plugin doesn't honour that. 

Attempting to translate this 
```
<string name="configuration_error_explaination">Your controller reported the following configuration error:<xliff:g>\n\n%1$s\n\n</xliff:g>Go into the Tuning section, fix the problem and power cycle your controller.</string>
 ```
into French gives
```
<string name="configuration_error_explaination">Votre contrôleur a signalé l'erreur de configuration suivante: <xliff: g> \ n \ n% 1 $ \ n \ n </ xliff: g> Allez dans la section Tuning, fixer le cycle de problème et la puissance de votre contrôleur.</string>
```
Which breaks the \n and the formatted number.

**Comment by Airsaid** [comment]
HI, you can update to V1.4, which adds support for the xliff:g tag.
