### ISSUE TITLE
Unescaped apostrophes

### ISSUE THREAD

**Issue by scudderfish** [Airsaid/AndroidLocalizePlugin#19]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x ] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:1.3
- IDE Version:Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic

#### Issue details
Following on from #18 the apostrophes in the translated text are not escaped and Android Studio marks them as an error.

**Comment by Airsaid** [comment]
Hi, you can update to V1.4 and set the xliff: g tag to ignore characters or text you don't want to translate.
