### ISSUE TITLE
中文转英文乱码

### ISSUE THREAD

**Issue by xiaohaibin** [Airsaid/AndroidLocalizePlugin#2]
![image](https://user-images.githubusercontent.com/11681218/45988465-b5fc0a80-c0a9-11e8-96ad-0e9a269c955d.png)

**Comment by Airsaid** [comment]
你好，目前只支持源翻译文件文本为英文，在后续版本中会支持其他语言。

**Comment by Airsaid** [comment]
已经支持，插件已升级到 1.1 版本。请重新安装最新版本。

**Comment by xiaohaibin** [comment]
好的，谢谢

**Comment by xiaohaibin** [comment]
转换还是有问题
