### ISSUE TITLE
如何设置不翻译的标签，有一些css标签也给翻译了

### ISSUE THREAD

**Issue by Dboy233** [Airsaid/AndroidLocalizePlugin#20]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:1.3
- IDE Version:3.5.0

#### Issue details
_Please provide the details of your issue_

css标签页被翻译了，如何避免 ：
\<string name="ok">\<u>\<big>\</big>\</u>\</string>

\<string name="ok">\<u><大>\</大>\</u>\</string>

**Comment by Airsaid** [comment]
你好，你可以更新到 V1.4 版本，然后使用  xliff:g 标签忽略不想被翻译的字符或文字。
