### ISSUE TITLE
设置代理后依然翻译后内容为空

### ISSUE THREAD

**Issue by dhhAndroid** [Airsaid/AndroidLocalizePlugin#22]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ ] Android Studio  3.5.3

#### Version of Plugin and IDE
- Plugin Version: 1.4
- IDE Version: 3.5.3

#### Issue details
使用插件 1.4版本 设置代理后，依然翻译为空，无法使用

**Comment by Airsaid** [comment]
更换代理 IP 试试呢？

**Comment by Airsaid** [comment]
如果没有问题我就先关掉了，有问题可以你可以再次打开。
