### ISSUE TITLE
大部分无法翻译、翻译慢和卡死

### ISSUE THREAD

**Issue by MrYZJ** [Airsaid/AndroidLocalizePlugin#24]
我在批量翻译时，导致AS直接卡死；还有就是虽然标了很多种语言，实际只要少数能正常翻译，其他的都是翻译出来都是空的

**Comment by strangeTail** [comment]
没用啊，卡死了

**Comment by welcomeworld** [comment]
> 没用啊，卡死了

https://github.com/welcomeworld/AndroidLocalizePlugin 可以试试这个，然后就是不要有 <string name="empty"> </string>这种空的字符串

**Comment by welcomeworld** [comment]
> > 没用啊，卡死了
> 
> https://github.com/welcomeworld/AndroidLocalizePlugin 可以试试这个，然后就是不要有 这种空的字符串

指完全空白的字符串<string

**Comment by Airsaid** [comment]
V2.0.0 版本已经更新，可以试下，自己申请 Key，切换到其他的翻译器。
