### ISSUE TITLE
如何仅翻译新增的字符，而不对已有的进行翻译和覆盖

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#26]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by Airsaid** [comment]
不要勾选「Overwrite Existing String」选项。

**Comment by qyzhaojinxi** [comment]
但是测试后发信其他已翻译的还是被覆盖了，而且strings.xml文件中本来已存在的一些注释文字也被删除

**Comment by Airsaid** [comment]
那就是 Bug 了，这个库已经有 3 年时间了，我最近正在对其进行重构，到时会顺带修复该问题。

修复前先重新打开了。

**Comment by Airsaid** [comment]
V2.0.0 版本已经更新，现在「Overwrite Existing String」选项的粒度更细了，不会存在还会覆盖的问题。

关于注释的问题，源文件（即 values/strings.xml）中不会改动，但是其他 strings.xml 文件不会保留注释信息（不需要也没有必要在每个文件中保留注释）。
