### ISSUE TITLE
英语句子标点符号后有空格的，会被截断

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#27]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

英文句子句子中在标点符号后，如果有空格，会被截断，仅翻译前半部分

**Comment by Airsaid** [comment]
请提供下原句子和翻译结果句子。

**Comment by qyzhaojinxi** [comment]
似乎是因为句子比较长？短一点的试了下没问题

The BT download process may be very slowly at first, then faster and faster. Please be patient.

翻译后：

BT下载过程首先非常缓慢，然后更快更快。

**Comment by Airsaid** [comment]
V2.0.0 版本已经更新，可以试试是否还存在这种问题。
