### ISSUE TITLE
1.1 版本 中文转英文还是有问题

### ISSUE THREAD

**Issue by xiaohaibin** [Airsaid/AndroidLocalizePlugin#3]
![image](https://user-images.githubusercontent.com/11681218/45990213-a680bf80-c0b1-11e8-9de0-ab3854451b1f.png)

**Comment by Airsaid** [comment]
你好，谢谢反馈。从你的截图来看并不是中文转英文的问题。由于与标题无关，因此我会先关闭该 isses。

该问题是由于太频繁请求翻译接口导致被临时拒绝访问。建议你明天再试试。目前该问题已经在解决当中，在之后会进行更新。

**Comment by xiaohaibin** [comment]
好的，确实当本地strings文件内容过多时，翻译有点慢
