### ISSUE TITLE
百度翻译报错

### ISSUE THREAD

**Issue by fqz100** [Airsaid/AndroidLocalizePlugin#30]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version: 2.0.0
- IDE Version: 4.2.1

#### Issue details
百度翻译报错：Invalid Access Limit(54003)

**Comment by Airsaid** [comment]
百度翻译[官方文档](https://fanyi-api.baidu.com/doc/21)对于该错误码的解释是：

> 访问频率受限：请降低您的调用频率，或进行身份认证后切换为高级版/尊享版。

**Comment by Airsaid** [comment]
我的建议是：首次翻译时，可以降低每次翻译的文本数量。

或许我后面可以新增一个设置选项，设置每次翻译后的间隔时间，避免短时间内翻译量过大的问题。

**Comment by fqz100** [comment]
好的，我试下。

> 我的建议是：首次翻译时，可以降低每次翻译的文本数量。
> 
> 或许我后面可以新增一个设置选项，设置每次翻译后的间隔时间，避免短时间内翻译量过大的问题。
