### ISSUE TITLE
长句子带特殊符号标签翻译失败

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#32]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:2.2.0
- IDE Version:

#### Issue details
_Please provide the details of your issue_

com.airsaid.localization.translate.TranslationException: Failed to translate "Over " text from Auto language to Arabic language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

下边是完整句子：

  <string name="delete_incomplete_content">Over <xliff:g id="count">%1$d</xliff:g> users download this file in 24 hours and <xliff:g id="percent">%2$d%%</xliff:g> downloads success.
Recommed you to wait patiently. </string>

**Comment by Airsaid** [comment]
使用的是哪一个翻译器呢？

**Comment by qyzhaojinxi** [comment]
我没设置这块，应该是默认谷歌，我看界面下边写的power by google

**Comment by Neo-Turak** [comment]
谷歌翻译出问题了。提示已经超过了次数。再后来就算上面的一样。

**Comment by Airsaid** [comment]
这是由于同一时间大量的请求，导致后面的请求重定向到了错误页面导致的。

建议切换到其他翻译器，例如百度翻译器后再次尝试。

**Comment by qyzhaojinxi** [comment]
好的
