### ISSUE TITLE
为什么转换后出现乱码呢

### ISSUE THREAD

**Issue by GAOli-cong** [Airsaid/AndroidLocalizePlugin#33]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [√ ] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:2.2.0
- IDE Version:4.1

#### Issue details
_Please provide the details of your issue_
不知道是操作不对嘛，转换后values语言乱码
如“\u5378\u8F7D\u5E94\u7528”这样显示。

**Comment by Airsaid** [comment]
你是英文转中文？

**Comment by GAOli-cong** [comment]
> 你是英文转中文？\u5378\u8F7D\u5E94\u7528 是 Unicode 码，看看自己的设置是否是 UTF-8 编码？如果不是的话切换到 UTF-8 编码。

我是中文转换为英文，as的编码格式也设置为utf-8啦~,生成后还是Unicode

**Comment by Airsaid** [comment]
看起来这是一个 Bug，我稍后会修复它。

**Comment by GAOli-cong** [comment]
> 看起来这是一个 Bug，我稍后会修复它。
谢谢大佬~~~

**Comment by GAOli-cong** [comment]
> 看起来这是一个 Bug，我稍后会修复它。

请问大佬，大约啥时候修复呀？我要不就试着改变一下as版本

**Comment by Airsaid** [comment]
不要着急，等我下班了改改。

**Comment by Airsaid** [comment]
感谢反馈，V2.2.1 版本修复了该问题：https://github.com/Airsaid/AndroidLocalizePlugin/releases/tag/v2.2.1
