### ISSUE TITLE
能不能自己指定翻译渠道 大佬

### ISSUE THREAD

**Issue by DeveloperZH** [Airsaid/AndroidLocalizePlugin#34]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by Airsaid** [comment]
你希望指定哪种翻译渠道呢？目前支持四种翻译：Google、Microsoft、百度、有道。

**Comment by DeveloperZH** [comment]
自己指定翻译库
有些公司有自己的翻译库

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Airsaid ***@***.***&gt;
发送时间: 2021年7月6日 14:13
收件人: Airsaid/AndroidLocalizePlugin ***@***.***&gt;
抄送: DeveloperZH ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Airsaid/AndroidLocalizePlugin] 能不能自己指定翻译渠道 大佬 (#34)





 
 你希望指定哪种翻译渠道呢？目前支持四种翻译：Google、Microsoft、百度、有道。

**Comment by Airsaid** [comment]
自己翻译库的话，每个都是人工翻译的？这种我觉得应该使用那种导入、导出的插件，可以看看这个项目：https://github.com/zhaoyubetter/ExtractMultiString。
