### ISSUE TITLE
翻译失败

### ISSUE THREAD

**Issue by git-maven** [Airsaid/AndroidLocalizePlugin#35]
![image](https://user-images.githubusercontent.com/45022397/126760933-6aaefcf4-5373-48ae-821a-81580977d732.png)

**Comment by Airsaid** [comment]
出现 429 是由于请求次数过多，导致暂时无法翻译。解决方法：

1、稍后再次尝试翻译。
2、切换到其他翻译器。

另外，设置页面可以将翻译间隔时间设置的更长一些，尽量避免触发该问题。
