### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by omkar-tenkale** [Airsaid/AndroidLocalizePlugin#37]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ x] Android Studio

#### Please select the translator to use
- [ ] Google
#### Version of Plugin and IDE
- Plugin Version:2.3.0
- IDE Version:2020.3.1

#### Issue details

Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "Call" text from Auto language to Afrikaans language: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=af&client=gtx&dt=t&dj=1&ie=UTF-8&oe=UTF-8&tk=756340.876666

**Comment by Airsaid** [comment]
The same issue: https://github.com/Airsaid/AndroidLocalizePlugin/issues/36
