### ISSUE TITLE
cannot retry due to redirection, in streaming mode

### ISSUE THREAD

**Issue by omkar-tenkale** [Airsaid/AndroidLocalizePlugin#38]
Please ensure you have given all the following requested information in your report.
Please select the affected platforms

    [ x] Android Studio

Please select the translator to use

    Google

Version of Plugin and IDE

    Plugin Version:2.3.0
    IDE Version:2020.3.1

Issue details

Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "Text Symbol" text from Auto language to Marathi language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Airsaid** [comment]
This is caused by a large number of requests at the same time, causing the later requests to redirect to the wrong page.

The solution can be seen in this issue: https://github.com/Airsaid/AndroidLocalizePlugin/issues/36

**Comment by Poul-xtf** [comment]
I also have this problem, how can I solve it
