### ISSUE TITLE
关于字符乱码的建议

### ISSUE THREAD

**Issue by 1993hzw** [Airsaid/AndroidLocalizePlugin#4]
作者的这个插件挺不错的。使用过程中有点小问题，字符乱码了，在此给下建议哈.

修改TranslateTask这里类里面的write()方法，在写文件时指定utf-8编码:

try (BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file, false), "UTF-8"))) {
                  ...
                } catch (IOException e) {
                    e.printStackTrace();
                }

代码亲测有效（我fork了项目，针对我想要的效果改进了下）

**Comment by Airsaid** [comment]
非常感谢你的使用和反馈！但是我并没有复现你所说的问题，能麻烦你提供下出现该问题的字符和操作步骤吗？

**Comment by LillteZheng** [comment]
ps，我在  file encoding 都统一设置成 UTF-8 了

**Comment by Airsaid** [comment]
感谢反馈。最新版已经修复，可以安装最新版试试。
