### ISSUE TITLE
翻译都是空白的，

### ISSUE THREAD

**Issue by ChloeDimen** [Airsaid/AndroidLocalizePlugin#40]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [√ ] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ √] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:3.4.2
- IDE Version:183

#### Issue details

1.版本是1.5的，翻译都是空白如下图：
![1633943124(1)](https://user-images.githubusercontent.com/20109490/136763656-2b1af1ac-97b4-4171-ab84-04876807685b.jpg)
2.Android Localize 没有翻译的渠道选择如下图
![image](https://user-images.githubusercontent.com/20109490/136763875-4ed69691-6717-49a9-9c2a-dc313413daca.png)
3.下载2.3.0的版本安装报如下错误
![image](https://user-images.githubusercontent.com/20109490/136763961-d080d855-2712-41b0-8307-bece6134eaf8.png)

**Comment by Airsaid** [comment]
目前最新版本是 2.3.0，升级到最新版本再试试吧。

**Comment by ChloeDimen** [comment]
Android studio升级到最新版本
报以下问题
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "AisemiMulti" text from Auto language to Chinese Traditional language: java.net.SocketTimeoutException: connect timed out
