### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Weehow** [Airsaid/AndroidLocalizePlugin#41]
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "SystemService" text from Auto language to Chinese Simplified language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by wolecode** [comment]
I got this same Exception when I tried using this plugin.

**Comment by KostyaM** [comment]
Same thing

**Comment by Airsaid** [comment]
Please check the "Use google.com" button and retry:

![image](https://user-images.githubusercontent.com/15967150/139655438-55f96a5c-8888-45d7-bfb0-f5e15ac4d765.png)

**Comment by wolecode** [comment]
I have checked the "Use google.com" and the error still persists. Do I need to change any other settings on android studio?
By the way, I am using Android studio arctic fox 2020.3.1

**Comment by Airsaid** [comment]
If it still doesn’t work, please switch to another translator. You need to apply for the translation key yourself. Because you use your own key, it will be more stable.

**Comment by iusama46** [comment]
After Checking Use google.com. It's working fine for me.

**Comment by 471448446** [comment]
work！
