### ISSUE TITLE
Invalid Sign(54001) error

### ISSUE THREAD

**Issue by kamaravichow** [Airsaid/AndroidLocalizePlugin#43]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Microsoft
- [x] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version: LATEST
- IDE Version: ArticFox 2020.3.1

#### Issue details
_Please provide the details of your issue_

```
Failed to translate "App" text from Auto language to Korean language: Invalid Sign(54001)
```
Error code appears

**Comment by Airsaid** [comment]
Please check if your appid and key are correct?
