### ISSUE TITLE
Plurals removed in generated xml, spaces between lines in xml also removed

### ISSUE THREAD

**Issue by Turalllb** [Airsaid/AndroidLocalizePlugin#46]
![image](https://user-images.githubusercontent.com/28982210/149904874-a1bf4d84-4006-4853-ab0a-e6241e03415c.png)

Plurals removed in generated xml, spaces between lines in xml also removed

**Comment by Turalllb** [comment]
I'm trying to solve these problems myself, I cloned the repository, but I can't figure out how to find these spaces between tags

**Comment by Airsaid** [comment]
Currently, only string tag strings are supported. Also, comments and line feeds are not preserved.

**Comment by Airsaid** [comment]
Added support for plurals and stirng-array tags in v2.4.0.

Node: Due to the need for review, you may need to wait for two business days before you can update online.

**Comment by Turalllb** [comment]
Bug when translating plurals
