### ISSUE TITLE
能否只针对我新增的或有修改的进行翻译

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#48]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:最新
- IDE Version:最新

#### Issue details
_Please provide the details of your issue_

能否仅针对新增的或修改的进行翻译，而不改变其他的，因为翻译文件中往往有一些特殊符号或其他内容，一更改会出问题。

所以能不能有一个选项支持仅插入新增的翻译结果，或者能够让用户选择想要翻译修改的字符串

**Comment by Airsaid** [comment]
选择翻译语言的弹框中，有一个「Overwrite Existing String」的勾选框（默认是不勾选的），如果未勾选，那么当目标文件中已经存在要翻译的字符串时，就不会进行翻译，而是直接使用。

新增的情况，如果未勾选「Overwrite Existing String」，那么就能达到你说的情况。

修改的情况，建议直接删除旧的条目并增加新的条目（需要保证 name 不同）。

**Comment by qyzhaojinxi** [comment]
测试了，但是会导致已经有的被修改，比如有些带特殊符号的

**Comment by Airsaid** [comment]
可以给出一些示例吗？如果是例如 xliff:g 之类的标签，翻译后的文本中不会保留。

**Comment by Airsaid** [comment]
可以关注一下  v2.5.0 版本，该版本不会修改被翻译文件中例如注释、空行、标签等内容，仅会修改需要翻译的内容。

**Comment by qyzhaojinxi** [comment]
好的，感谢，我试试
