### ISSUE TITLE
Code question. 

### ISSUE THREAD

**Issue by Turalllb** [Airsaid/AndroidLocalizePlugin#49]
Why did you introduce AbstractValue entities when you can work with XmlTag? Instead of keeping copies of the xmlTag , you write their text into your own entities, overwrite attributes, such as translatable, then translate and manually add the necessary tags back, such as <strings> . I think you've made it more difficult.

**Comment by Turalllb** [comment]
![image](https://user-images.githubusercontent.com/28982210/152186211-9eead2e1-4e1c-434b-a86f-6c52f24da203.png)
I understand why you did this, because all tags and string and plurals are one XmlTag type, but pay attention to this xmlTag with a different name, somewhere string , and somewhere plurals. You could use them. Plus, it becomes possible to easily add to the list and type XmlComment and XmlText, which stores line breaks and spaces

**Comment by Turalllb** [comment]
![image](https://user-images.githubusercontent.com/28982210/152193804-f4a779eb-c7e1-4322-b962-7f45f3e780f7.png)

**Comment by Airsaid** [comment]
The original design was for decoupling code, but so far it looks like an overdesign. I saw your PR and have merged it. Thanks for contributing code!
