### ISSUE TITLE
翻译全是乱码

### ISSUE THREAD

**Issue by zoubihai** [Airsaid/AndroidLocalizePlugin#5]
<resources>
	<string name="server_client_id">��Q���_�l���Լ���Ո��server_client_id</string>
	<string name="facebook_app_id">��Q���_�l���Լ���Ո��appid</string>
	<string name="fb_login_protocol_scheme">��Q���_�l���Լ���Ո��protocol_scheme</string>
</resources>

**Comment by Airsaid** [comment]
你好，感谢反馈！请提供更多的信息帮助我排查问题：

1. 当前使用的插件版本。
2. 当前 IDE 的编码设置。
3. 乱码字符翻译前的字符。
4. 所有字符都乱码还是只是特定的字符？

**Comment by zoubihai** [comment]
1.插件版本是1.1;
2.utf-8;
3.<resources>
    <string name="server_client_id">替换为开发者自己申请的server_client_id</string>
    <string name="facebook_app_id">替换为开发者自己申请的appid</string>
    <string name="fb_login_protocol_scheme">替换为开发者自己申请的protocol_scheme</string>
</resources>
4.中文相关的都是乱码

**Comment by Airsaid** [comment]
1.2 版本中已经修复了乱码问题，请使用 1.2 版本后再试试。

**Comment by zoubihai** [comment]
好的,我试试

**Comment by Airsaid** [comment]
没有问题的话我就先关闭 issue 了。
