### ISSUE TITLE
Translatable = false string in all translation files should not be

### ISSUE THREAD

**Issue by Turalllb** [Airsaid/AndroidLocalizePlugin#51]
![image](https://user-images.githubusercontent.com/28982210/154659854-81e3dbb0-5158-4350-bf29-bdf53765fe85.png)

such a string should not be included in all translation files, but stored only in the default one. The situation when this line is not in the default language (eng), but it is in another file with the translatable = false flag is impossible.

**Comment by Airsaid** [comment]
If not retained, it may leave a lot of gaps. It is also easier to compare the two sides if you keep it, which seems to have more advantages than disadvantages.
