### ISSUE TITLE
Question about translating a specific string

### ISSUE THREAD

**Issue by Turalllb** [Airsaid/AndroidLocalizePlugin#52]
Tell me if it will be difficult to implement such a function: When you click on the string tag, call up a menu for translating this particular string into other languages. This function is needed when the text of some line has been changed and it needs to be changed in all other languages. In such a situation, it is not reasonable to call a complete overwrite of the entire file, because there are texts that professional translators have worked on.

**Comment by Airsaid** [comment]
Calling out the menu is not a good solution, it leads to an increase in the number of operation steps.

In a later version, it will be possible to use this feature directly if an entry is already translated, and only translate entries that do not exist.
