### ISSUE TITLE
Single quote character must be escaped in strings.xml

### ISSUE THREAD

**Issue by pdalfarr** [Airsaid/AndroidLocalizePlugin#54]
First, thanks a lot for this great plugin: amazing :-) 

#### Please select the affected platforms
- N/A

#### Please select the translator to use
- N/A

#### Version of Plugin and IDE
- Plugin Version: 2.5.0
- IDE Version: Android Studio Bumblebee | 2021.1.1 Patch 2

#### Issue details
Translation result containing single quote characters should contain 'escaped single quote'.
Full list of 'special characters' which need to be escpaed is availalbe here: https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes . 
(single quote, double quotes, etc...)

Example:

English source
	`<string name="contacts_select_contact_fragment_text_hint">I enter the name of the contact here</string>`

French result (when using this plugin):
	`<string name="contacts_select_contact_fragment_text_hint">J'entre le nom du contact ici</string>`

which is not correct.
Instead of "j'entre", we should have **"j\\'entre"** because **single quote must be escaped** in strings.xml.
Result should be:
	`<string name="contacts_select_contact_fragment_text_hint">J\'entre le nom du contact ici</string>`

**Comment by Airsaid** [comment]
Hi, pdalfarr. Thank you for using it!

This is a good feedback, I will optimize it in the next version!

**Comment by pdalfarr** [comment]
Hi,

I confirm this must be done for single quote.
For double quotes I just tried in Android Studio: it looks like Android Studio accept them even if they are not escaped.

Anyway, as I wrote before, all cases are listed here: https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes 

Thanks again for this plugin 👍
