### ISSUE TITLE
里面是空的标签

### ISSUE THREAD

**Issue by 13297063206** [Airsaid/AndroidLocalizePlugin#55]
<string name="app_no_data">暂无数据</string>
得到的string文件里面都没有翻译，啥情况？？？

新生产的文件里面都是这样。。。。。。。。。。。。
<string name="app_no_data"></string>

**Comment by Airsaid** [comment]
请提供下更详细的信息：

1、使用的插件版本
2、AndroidStudio 版本
3、使用的翻译器

**Comment by 13297063206** [comment]
implementation 'com.github.jokar:multi-languages:0.1.5'
android studio3.6.1
没有用啥翻译器。
怎么配置翻译器？

**Comment by Airsaid** [comment]
你提供的这个依赖库：com.github.jokar:multi-languages:0.1.5 和 AndroidLocalize 插件没有关系。。。

在 AndroidStudio 的设置页面 -> Plugins 下搜索 AndroidLocalize 可以看到插件的版本。

在设置页面 -> Tools -> AndroidLocalize 中可以配置插件。

**Comment by 13297063206** [comment]
我是用的这个AndroidLocalize ，是在这里配置的

**Comment by Airsaid** [comment]
你还没有提供你使用的插件版本，检查你的插件版本是否是最新的。

**Comment by 13297063206** [comment]
1.5的，最新的

**Comment by 13297063206** [comment]
是因为我没有配置啥翻译器吗？没看到你这个插件有配置的地方啊

**Comment by Airsaid** [comment]
1、截止目前最新版本是 V2.5.0，不是 V1.5；
2、上面已经描述了插件配置的位置。

**Comment by 13297063206** [comment]
我知道了，在tool里面还有配置是吧，但是我的studio是3.6的，好像没有你的gennarel选项，而是proxy setting

**Comment by 13297063206** [comment]
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "平板" text from Auto language to Chinese Traditional language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Airsaid** [comment]
你的插件版本太低，所以没有该设置选项，升到最新版本来吧。

**Comment by 13297063206** [comment]
上面是升级到4.2之后的版本，插件是2.5但是报错
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "平板" text from Auto language to Chinese Traditional language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

翻译不了

**Comment by Airsaid** [comment]
这是一个新的问题。使用自己的翻译账号，并切换到其他的翻译器可解决。

**Comment by 13297063206** [comment]
用了百度账号
报错
Translation error: java.lang.ClassCastException: class com.intellij.psi.impl.source.PsiPlainTextFileImpl cannot be cast to class com.intellij.psi.xml.XmlFile (com.intellij.psi.impl.source.PsiPlainTextFileImpl and com.intellij.psi.xml.XmlFile are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @75881071)

**Comment by 13297063206** [comment]
Plugin Error: Plugin "Android Localizationer" is incompatible (supported only in IntelliJ IDEA).
