### ISSUE TITLE
修复了Google免费翻译和百度API翻译

### ISSUE THREAD

**Issue by YaronWong** [Airsaid/AndroidLocalizePlugin#57]
Please ensure you have given all the following requested information in your report.

修复了Google免费翻译和百度API翻译，正常使用，已申请PR
代码糙，可以参考新URL 修复
感谢作者~
https://github.com/YaronWong/AndroidLocalizePluginFix?organization=YaronWong&organization=YaronWong

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Microsoft
- [x] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by Airsaid** [comment]
Hi，感谢贡献 PR～

能简单描述一下 Google 免费翻译和百度 API 翻译目前出现的问题吗？

**Comment by YaronWong** [comment]
Hi 
Google 免费翻译 ，一个单词报错，一直卡住，无法正常翻译出结果，不确定是不是接口无法使用。
百度 API ，我申请新建了翻译项目，填写了2个key，也是无法正常翻译，报错翻译出错卡住，
查看了百度翻译的文档，发现目前文档接口地址不一致，我就改了，先申请token，再翻译，正常。
现在用的新地址：
google翻译：https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl=auto&tl=zh-cn&q=dog
百度翻译文档：https://ai.baidu.com/ai-doc/MT/4kqryjku9
如果你这里使用正常，可以无视 ：）

**Comment by Airsaid** [comment]
我看了一下，发现你给的百度翻译的文档与我接入的平台不同。一个是百度 AI 平台的翻译，一个是百度翻译开放平台。两边的接口是不同的，百度翻译开放平台的文档：http://api.fanyi.baidu.com/doc/21

所以这就导致你在另一个平台申请的账号无法在插件中使用。以及，我刚刚再次使用我的账号测试过百度翻译，是没有问题的。

另外 Google 免费翻译，由于这种方式需要经常更新 token 的获取方式，所以在我个人精力有限的情况下，不打算一直维护 Google 免费翻译，还是推荐大家选择适合自己的翻译平台，申请自己的翻译账号，使用自己的账号来翻译。

**Comment by YaronWong** [comment]
原来是平台服务不同，那没事了
Google免费版的，我找到2个接口，但是不保证什么时候封
同样推荐自己申请使用付费服务
OK ，那就这样吧，PR忽略
再次感谢！
