### ISSUE TITLE
amdroid studio 版本 2021.1.1  patch 2

### ISSUE THREAD

**Issue by litaoyuan** [Airsaid/AndroidLocalizePlugin#58]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

翻译英语出错
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "我是测试" text from Auto language to English language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by litaoyuan** [comment]
Plugin Version 2.5.0

**Comment by Airsaid** [comment]
建议切换到其他的翻译器进行翻译。
