### ISSUE TITLE
默认勾选已有的语言

### ISSUE THREAD

**Issue by allentown521** [Airsaid/AndroidLocalizePlugin#59]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ ] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
这是一个feature，现在翻译的时候国家是自己去选择的，但是实际使用很麻烦，比如我有一个项目已经接入了几十个国家了，那么翻译的时候我需要一个个选择这些国家，但是切换其他项目的时候呢又需要修改，来来回回人就疯了。

是否可以从strings文件列表去查找在项目中已经使用的国家，默认直接勾选上，这样事半功倍

**Comment by Airsaid** [comment]
这是一个很好的建议，在后面的版本中会考虑加上该功能。
