### ISSUE TITLE
看了里面好像是使用的谷歌翻译，使用的时候会等待很长时间，希望可以做一个使用百度翻译的插件，楼主加油

### ISSUE THREAD

**Issue by lvzhihao100** [Airsaid/AndroidLocalizePlugin#6]
IDE Info:

Plugin Version:

Issue Description:

**Comment by Airsaid** [comment]
你好，感谢你的使用～ 在最开始写这个插件时就考虑到了多翻译器的情况，但是最后只提供了 Google 翻译，因为其支持的翻译国家最多。后面可能会提供选项切换为其他翻译器，但是可翻译的国家会大大减少。有利有弊，因此会再考虑后再决定是否添加。
