### ISSUE TITLE
建议支持可在任意value目录下点击翻译

### ISSUE THREAD

**Issue by wjploop** [Airsaid/AndroidLocalizePlugin#62]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Microsoft
- [x] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
默认value目录下为英文，以致只能从英文翻译成各个目标语言。一般项目中，简体中文和英文已存在人工核对，无需插件翻译，而当从英文 > 繁体中文时，会出现简体和繁体词意相差较大的问题。比如这个单词， “general” > “通用” > “將軍” ，这是英文>繁体所致，假设能支持简体>繁体，就不会出现这样的情况。

当然，也可以把简体的string.xml拷贝到默认的value目录后再翻译成繁体，但这增加了不少的工作量，故希望支持各个value目录作为源语言翻译。

**Comment by Airsaid** [comment]
这个问题的核心原因还是因为翻译器本身不准确的问题，即使使用其他目录作为源语言，也可能还会出现其他翻译不准确的问题。所以暂时不会考虑这个 feature。
