### ISSUE TITLE
java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

### ISSUE THREAD

**Issue by JackeyAndev** [Airsaid/AndroidLocalizePlugin#63]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao

#### Version of Plugin and IDE
- Plugin Version: 2.5.0
- IDE Version: AS Chipmunk|2021.2.1

#### Issue details
Translation error: com.airsaid.localization.translate.TranslationException: Failed to translate "xxxxx" text from Auto language to Afrikaans language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by Swordox972** [comment]
It did the same to me. Hopefully, there is a solution. Go to File -> Settings -> Tools -> AndroidLocalize -> click on Use google.com. After this it works. 
Note: The plugin was a little slow for me to translate so just wait few minutes.

**Comment by Airsaid** [comment]
duplicated: #41
