### ISSUE TITLE
Support no translation of existing string.

### ISSUE THREAD

**Issue by Swordox972** [Airsaid/AndroidLocalizePlugin#64]
Please ensure you have given all the following requested information in your report.

- [ ] Android Studio

- [ ] Google (API)

#### Version of Plugin and IDE
- Plugin Version: 2.6.0
- IDE Version: 2021.2.1

#### Issue details
How to simply translate one String into another languages and not overwrite the existing strings translated as the Google Api is only 10$ free per months.

**Comment by Airsaid** [comment]
There is already support for not translating already existing strings.

You just need to uncheck the "Overwrite Existoin String" option:
![image](https://user-images.githubusercontent.com/15967150/175193604-0da4c3f4-3e84-43a4-ab26-bcb818e4d7ae.png)

Moreover, the plugin also supports caching, which can be set in the settings to avoid repeated translations.
