### ISSUE TITLE
Localisation is not working

### ISSUE THREAD

**Issue by Manpreet7377** [Airsaid/AndroidLocalizePlugin#66]
Getting the following error while translating languages:-

Translation failure: Failed to translate "Mark as done" text from Auto language to Telugu language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode.

Could you please help me out to resolve this problem.
Android Studio version:- Android Studio Chipmunk | 2021.2.1 Patch 1

**Comment by Airsaid** [comment]
I need more information from you.

1. what is the version of the plugin you are currently using?
2. and IDE version?
3. which translator is being used?

**Comment by Manpreet7377** [comment]
AndroidLocalize plugin version is 2.6.0, And I am using Chipmunk Android Studio with 2021.2.1 Patch 1 version. Just want to convert string file to required language using this plugin.

**Comment by Airsaid** [comment]
You can try switching to other translators in the settings page for translation.

**Comment by cornflower10** [comment]
I encountered the same error, how to solve it

**Comment by arsalrao** [comment]
I also encountered the same issue.
`Translation failure: Failed to translate "Please Enter Description" text from Auto language to Arabic language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode`

**Comment by Airsaid** [comment]
As I said above, switch to another translation engine on the settings page and use the account id and key you applied for.
