### ISSUE TITLE
Rich text not translate

### ISSUE THREAD

**Issue by caojianhua** [Airsaid/AndroidLocalizePlugin#67]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version: 2.6.0
- IDE Version: Android Studio Chipmunk

#### Issue details
Rich text such as:
```
<string name="note"><Data><![CDATA[Success, <font color="#ff0000">%s%s</font> removed!]]></Data></string>
```

**Comment by Airsaid** [comment]
It is not supported yet, it will be supported in the next version.
