### ISSUE TITLE
百度翻译，链接失败，日志如下：

### ISSUE THREAD

**Issue by qingqingandroid** [Airsaid/AndroidLocalizePlugin#68]
Translation failure: Failed to translate "Yiqikan" text from Auto language to Chinese Simplified language: java.net.ConnectException: Connection refused: connect

**Comment by Airsaid** [comment]
提问的时候不要删除掉 issue 模版的信息，因为其中标注了需要你提供的更完善的信息。

1. 当前使用的插件版本？
2. 当前使用的 IDE 信息？

**Comment by Airsaid** [comment]
由于太久没有收到更多的提供信息，我先关闭该 Issue 了。如果后续有问题可以再次打开。
