### ISSUE TITLE
您好，插件无法使用。要么studio卡死，要么生成的翻译文件没有翻译文本。

### ISSUE THREAD

**Issue by wbb631094818** [Airsaid/AndroidLocalizePlugin#7]
1. studio版本：3.0.1
2. 插件版本：1.3

求帮助！

**Comment by wbb631094818** [comment]
![446b1cdf-513c-4564-aebd-bb94b2bccda6](https://user-images.githubusercontent.com/19794110/47473171-1b2b5300-d844-11e8-824e-45bbdecb8180.png)

**Comment by Airsaid** [comment]
你好，出现该情况是因为频繁请求翻译接口导致，目前的临时解决方法是稍等一天左右再尝试。如果需要翻译的字符串或国家太多，可分次尝试。

在后续的版本中会解决该问题，到时会在该 issue 通知。

**Comment by cyhwtc** [comment]
插件无法使用,studio卡死

**Comment by lgengsy** [comment]
怎么分次尝试啊。

**Comment by SuperNoodleMan** [comment]
这个问题已经过去8个月了   到现在没有解决啊  ?  按你们的说法 还是不行  有人处理吗?

**Comment by KnIfER** [comment]
使用高级点的vpn的话换个节点重新开始。
否则就小心翼翼控制一次翻译的数量
测试下来，一次翻译二十个语言，十个1~4个单词组成的语句，完全没有问题。
谨慎点的话，我看一次翻译十个语言，每次翻译十个句子吧。。。
可以试试我改的插件
https://github.com/Airsaid/AndroidLocalizePlugin/issues/21
https://github.com/KnIfER/AndroidLocalizePlugin

**Comment by Airsaid** [comment]
V1.4 版本新增了代理功能，如果翻译为空字符，可以尝试添加代理解决。
