### ISSUE TITLE
Don't limit the translation option to selected file names

### ISSUE THREAD

**Issue by frogggias** [Airsaid/AndroidLocalizePlugin#75]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [X] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [X] Ali

#### Version of Plugin and IDE
- Plugin Version: 2.6.1
- IDE Version: Android Studio Electric Eel 2022.1.1 Canary 10

#### Issue details

In large projects is good practice to split translation into multiple files. The option to translate can be available for all value files.

**Comment by Airsaid** [comment]
Yes, you're right. I will consider removing that restriction in a later release.

**Comment by frogggias** [comment]
Awesome, thanks!
