### ISSUE TITLE
为什么不支持 例如 abc_strings.xml的一键翻译， 仅仅只支持 strings.xml文件的翻译？

### ISSUE THREAD

**Issue by DavidXuKui** [Airsaid/AndroidLocalizePlugin#77]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ ] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by DavidXuKui** [comment]
为什么不支持 例如 abc_strings.xml的一键翻译， 仅仅只支持 strings.xml文件的翻译？

**Comment by Airsaid** [comment]
已经支持，将会在下个版本中更新。

**Comment by DavidXuKui** [comment]
好的，请问下个版本的发布的时间节点是怎样的？

**Comment by DavidXuKui** [comment]
近期会发布新版本吗？

**Comment by DavidXuKui** [comment]
这个插件非常有用， 非常感谢作者

**Comment by Airsaid** [comment]
支持该功能的 v2.7.0 版本今天已经发布，预计明天通过审核，届时可以更新插件到最新版。
