### ISSUE TITLE
项目中往往有很多的文本资源文件， 例如 base_strings.xml,  common_strings.xml,  请增加这些文件的右键支持。

### ISSUE THREAD

**Issue by DavidXuKui** [Airsaid/AndroidLocalizePlugin#78]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [ ] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by Airsaid** [comment]
已经支持，将会在下个版本中更新。不要重复提 Issue 哈~ #77
