### ISSUE TITLE
不在Tools里面显示，也无法使用右键

### ISSUE THREAD

**Issue by CotTan** [Airsaid/AndroidLocalizePlugin#79]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
Android Studio

#### Please select the translator to use
 Google
 Google (API)
 Microsoft
 Baidu
 Youdao
 Ali

#### Version of Plugin and IDE
- Plugin Version: 2.5.0
- IDE Version: 4.1.1

#### Issue details
如下图，已经安装（已重启），但是不在Tools里面显示，在资源文件上右键也无选项，使用百度版的，语言种类比较少，还有次数限制。
![2022-10-09_181337](https://user-images.githubusercontent.com/11958737/194751125-eee438e5-86a7-4922-853b-ffdce346a288.png)
![2022-10-09_181400](https://user-images.githubusercontent.com/11958737/194751128-84a4f024-8dd7-47b2-9212-a061e18fb082.png)

**Comment by CotTan** [comment]
是先安装的原始版本，再安装百度的版本测试

**Comment by Airsaid** [comment]
截止目前插件最新版本是  v2.6.1，但是我看到截图中没有更新的选项，怀疑可能是 IDE 版本过低导致的问题。你可以试试升级下 AndroidStudio 的版本。

**Comment by CotTan** [comment]
但是在4.1.1版本下载的为啥不可以使用呢，理论来说，都支持下载了，应该可以使用。。。此版本确实没有更新选项

**Comment by Airsaid** [comment]
> 百度版本是截图中没勾选的那个，插件里面的链接地址 https://plugins.jetbrains.com/plugin/13290-androidlocalizewithbaiduapi ，我打不开，里面翻译的语种比较少，而且 还需要申请key，有点麻烦，刚刚去看最新版的AS，里面确实有2.7.0的版本

简单看了下，这个百度版本不是我这边维护的，看起来是基于我这个插件进行了二次开发。

不太清楚如果同时安装这两个插件会不会导致什么问题，例如 key 冲突之类的，所以建议还是只保留一个插件。

**Comment by Airsaid** [comment]
> 但是在4.1.1版本下载的为啥不可以使用呢，理论来说，都支持下载了，应该可以使用。。。此版本确实没有更新选项

目前最新版本的插件支持的最低 IntelliJ 平台版本是：2020.3，你可以在 AndroidStudio 关于页面查看是否满足，如果不满足的话肯定是没有升级选项的。

**Comment by Airsaid** [comment]
因为长时间没有回复，不知道你的问题是否已经解决？我这边先关掉该 issue 了，如果还有问题你可以再开启，有新问题也可以开一个新的 issue。
