### ISSUE TITLE
New feature(local feeder)

### ISSUE THREAD

**Issue by hocesjc** [Airsaid/AndroidLocalizePlugin#82]
Hi, I think it would be a nice feature to be able to feed the plugin a local translation file something like the cache

**Comment by Airsaid** [comment]
Hi, the caching feature is currently supported (enabled by default), and you can choose to turn it off or set the number of cached entries in the settings page.

**Comment by hocesjc** [comment]
I know that it has a cache, but I was referring to being able to put a file with translations, for example, you send a native translator to translate and you want him to use these translations first and if he does not have them, he should use another of the services

**Comment by Airsaid** [comment]
Oh, sorry I misunderstood what you meant. Do you mean to provide a local translation file, and when translating, give priority to getting the result from that file, and then go to the translation service when it is not available?

**Comment by hocesjc** [comment]
Exactly :)

**Comment by Airsaid** [comment]
What is the problem to be solved by doing so? 

If it is to solve the problem of inaccurate translation by the translation service, then you can modify the string resource file twice directly after the translation is completed, and the next translation will only translate the string entries that do not exist yet.

**Comment by hocesjc** [comment]
To reuse them in several apps and automate it, imagine that there are 10 apps in 20 languages, if they are also found in different files in a different way in each app. If you also added the feature https://github.com/Airsaid/AndroidLocalizePlugin/issues/81 you would only have to do one click vs reviewing file by file reviewing manually in a language that you may not even know.

**Comment by Airsaid** [comment]
I think I know what you mean, but this doesn't fit with the goal of the current plugin, which is more like what a translation management system should do.
