### ISSUE TITLE
I am trying to translate a recently created project, it gives me an error

### ISSUE THREAD

**Issue by juanclobato88** [Airsaid/AndroidLocalizePlugin#83]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version: 2.7.0
- IDE Version: 
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.github.airsaid.androidlocalize (2.7.0), org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46), com.github.platan.gradle-dependencies-formatter (0.6.1)

#### Issue details
Translation failure: Failed to translate "My Application" text from Auto language to Spanish language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode

**Comment by radoyi** [comment]
I have the exact same error. Not able to translate.

**Comment by Airsaid** [comment]
Hi, the FAQ explains the reasons and solutions for this problem, please check it carefully: https://github.com/Airsaid/AndroidLocalizePlugin#faq
