### ISSUE TITLE
open translations editor 这个选项打开后，列宽是固定的，每次都要再拉一下，希望优化一下，改成宽度自适应或者列宽再宽点

### ISSUE THREAD

**Issue by Liby94** [Airsaid/AndroidLocalizePlugin#9]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Version of Plugin and IDE
- Plugin Version:
- IDE Version:

#### Issue details
_Please provide the details of your issue_

**Comment by Liby94** [comment]
试着翻译了一下，真的卡死了

**Comment by Airsaid** [comment]
谢谢反馈，在之后会优化的。

**Comment by Airsaid** [comment]
你好，请更新到 V1.4 版本。
