### ISSUE TITLE
xliff标记的特殊符号会被翻译成别的

### ISSUE THREAD

**Issue by qyzhaojinxi** [Airsaid/AndroidLocalizePlugin#91]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [x] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

#### Version of Plugin and IDE
- Plugin Version:2.7.0
- IDE Version:Build #AI-213.7172.25.2113.9123335, built on September 30, 2022

#### Issue details

strings.xml文件中，%s和%d，已经被xliff标记，但还是被翻译成了别的语言，或者%c、%S等

已发现设涉及的语言包括：ar,bg,el,hi,it,ko,sr,vi
上线后就会报错
```
java.util.UnknownFormatConversionException: (Conversion = 'r')
at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2787)
at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2817)
```

**Comment by Airsaid** [comment]
感谢反馈~ 最近在找新工作比较忙，在找到工作后我会来看一下这块的问题。当然也欢迎提交 PR~

**Comment by Airsaid** [comment]
v2.9.0 版本中已经修复该问题。

**Comment by qyzhaojinxi** [comment]
感谢，辛苦啦
