### ISSUE TITLE
deepL pro support

### ISSUE THREAD

**Issue by hocesjc** [Airsaid/AndroidLocalizePlugin#92]
Hi,

The url of the deepL support is of free api but the pro url is different
https://www.deepl.com/pro-api?cta=header-pro-api
![imagen](https://user-images.githubusercontent.com/95121300/203002930-264ebd72-99bc-4281-9f3b-8d18f35afb13.png)
![imagen](https://user-images.githubusercontent.com/95121300/203002975-b80b1fe6-247b-4c83-ac67-da9766260a9f.png)

Thank you,

**Comment by Airsaid** [comment]
Thanks for the feedback! Support for DeepL Pro users will be added later.

**Comment by Airsaid** [comment]
Hi, 

DeepL Pro is supported in v2.9.0.
