### ISSUE TITLE
Translating\n problem

### ISSUE THREAD

**Issue by hocesjc** [Airsaid/AndroidLocalizePlugin#93]
Please ensure you have given all the following requested information in your report.

#### Please select the affected platforms
- [x] Android Studio
- [ ] IntelliJ IDEA

#### Please select the translator to use
- [ ] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali
- [x] DeepL

#### Version of Plugin and IDE
- Plugin Version: 2.8.0
- IDE Version: 2021.2.1 patch 2

#### Issue details
Problem translating \n
Original 
    <string name="share_app_text">Hi!\n\nDownload free AR Translator here:\n\n%s</string>
DeepL ge 
    <string name="share_app_text">Hallo! \n\nLaden Sie den AR Translator hier kostenlos herunter:\n\n%s</string> ok    
DeepL fr 
   <string name="share_app_text">Bonjour!\NTéléchargez gratuitement AR Translator ici : \n\N%s</string> Problem
Google fr    
   `  <string name="share_app_text"><![CDATA[Bonjour !\n\nTéléchargez le traducteur AR gratuit ici :\n\n%s]]></string>`
Google ko
    <string name="share_app_text">안녕하세요!\n\n여기에서 무료 AR 번역기를 다운로드하세요:\n\n%s</string> ok
DeepL pt
    <string name="share_app_text">Olá!nDownload gratuito do AR Translator aqui:n%s</string> problem
DeepL ru
    <string name="share_app_text">Привет!\n\nСкачать бесплатный AR Translator можно здесь:\n\n%s</string> ok
DeepL zh
    <string name="share_app_text">Hi!/n\nDownload free AR Translator here:/n\n%s</string> problem

**Comment by Airsaid** [comment]
For special characters like `\n`, it is better to keep them out of the translation. 

You can check the [FAQ](https://github.com/Airsaid/AndroidLocalizePlugin#faq) on how to keep the specified characters out of the translation.
