### ISSUE TITLE
Issue while translating to other language. 

### ISSUE THREAD

**Issue by zari786** [Airsaid/AndroidLocalizePlugin#96]
**Translation failure: Failed to translate "Downloader" text from Auto language to Afrikaans language: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode**

![androidversion](https://user-images.githubusercontent.com/34839678/205227052-90636cff-e984-452b-850c-1bd6cc7fba7b.PNG)

![android localize version](https://user-images.githubusercontent.com/34839678/205227060-87427c10-ca1b-4175-869a-0a269ff4532c.PNG)

#### Please select the translator to use
- [✅] Google
- [ ] Google (API)
- [ ] Microsoft
- [ ] Baidu
- [ ] Youdao
- [ ] Ali

**Comment by Airsaid** [comment]
Duplicate issue: https://github.com/Airsaid/AndroidLocalizePlugin/issues/83
